flags: {}
extra-package-dbs: []
packages:
- .
extra-deps:
- csound-expression-5.2.0
- csound-expression-dynamic-0.3.0
- csound-expression-opcodes-0.0.3.2
- csound-expression-typed-0.2.0.0
- csound-sampler-0.0.8.0
- data-fix-cse-0.0.2
- temporal-media-0.6.1
resolver: lts-8.13
